node_js:
- lts/*
addons:
  sonarcloud:
    organization: ferzerkerx-github
    token:
      secure: eD0NqSW5jIfcVKiSjsehiju/Nb7U6YRkjH3XkURJ5tKoIE5vDNpDfA/2Ff4hxjdHXaE+R9sKtivRVYvodrXwSGGJmZOtLfnrceKgFyQvYzK3/v1vtHwYF1iIYT1AIFz7M6Qz3Z67uZKLR+t+/1W4hPx370xosuNR9j28BQBHGYJAmS5iHQWBxwJ9AL4OyMegy0r+2ycSB60OFul3v+4jre1jWBxtVbklAwNOZ19XWMUlFdZ+YOBA+SmbTdNh2zKxzICQTTcnJ9/gpYfrEkHnXCNJ8BsRwJZAQCDWb9syYmXyoduhS6aXcjoNPD4v3TwTVj+YR0J9VM+KmB6FFzDb2+t1wTMQK5P0a5an6m3UdlFMsLrMX8d3FAwb0n3fxDFtCxmepP1sgcu76D4WdvedafbmbS1B3NEJhUbOW+7XqBqnk71d6WIlSA/zlXZ5+DjkxBBiAOiMmq1m9tjozISH/SVhdgBN4TnjWWASGawNB17onxUs8p1NJP7mENEMigYBcessleZucJyMT9Zd8miy3cvb7HLykQuutKWnlzdNyVxBPDGw+z4vgdWKDNiqvFLZhJoVABq8ks2sV8yizOm5XqYNhVLFaNww2CxlcLm+wml/+bZOQmtePuA32EL1Y7lE6ZLp/NxfRCmkfUoqxwMnU+PjvNHgnF8CE1fI6lOfyHw=
env:
  secure: nHomSoGEZziJ0esDtt8NwnPb8qE1vuhYUpPZwvJPjKEdrrWCkCh4xeSHWyq1+QK9FuGaCRRDH3N7QOYaHot0qSwv4qWfEj3rvdJkkkDHiNnksr9PhB/eSJjv490/woDnJSrJ1ia3tOvf5xk/AuXseptwDAtXEQVVWphjcngrEMtlKH6eN7SrEreAxX5vyxji2FGppTQI7DJ9Xiag4As5kTJtIaCe0Sf4LLl5IcoKFqBMaHGzSqL7jddvxq7oEWN5jH5vkkU/EAx1CI/qiqIPcgw3Sulw3m6TB01mRzMElxHZKZe+nhFDTi1RGm/nex+6AxDMnQwCGYEzDzNKxL3FasxbY0YKEU3id02hMzclx6JrexCC7uRInzf3KQc+1Y8yIlcDxOoMxkgF0kw5zNr7hefA/rma+YznM7h4TAVzs6YKNHTpjNAE26/eWPaLbEELFDNu9VAE9IDmVlja7mgq0Saw40IKAEg9d/EGF0ozidXnh0KmW3YVqK6tcoNLrPG/yvEI9b0K8qQPrVylJwXIT5fcAqQOeGvv7idsbexTutGx88vphJ1GfmMrHnPYdWnZouPXx23l1v6htF95H/plDBr2HfGY4oIEkX+9J8NjquPOg3VSb6fVwN3CQLImvG9B4DeYj4b/fSRRZygYESMQiaKY3aMUe92hAWxCHfbrUUc=
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g snyk
script:
- yarn build
- sonar-scanner

after_success:
- snyk monitor
